server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

mybatis:
  typeAliasesPackage: gomobility.office.model #实体类所在包
  mapperLocations: classpath:mapper/*.xml #配置文件所在包

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:sqlserver://47.108.141.120:1433;databaseName=Office
    username: admin
    password: 1#okrv2m8mmAxIX1*1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari:
    readOnly: false
    connectionTimeout: 15000
    idleTimeout: 6000000
    maxLifetime: 1800000
    maximumPoolSize: 15
  jackson:
    default-property-inclusion: non_null
    locale: zh
    time-zone: GMT+8
